### ISSUE TITLE
3.0.0 build broken (dependency on xen-gnt.unix)

### ISSUE THREAD

**Issue by cfcs** [mirage/ocaml-vchan#102]
```
#=== ERROR while installing vchan.2.3.0 =======================================#
# opam-version 1.2.0
# os           linux
# command      ./configure --enable-xenctrl --enable-xen
...
### stdout ###
# Looking for xenctrl.h: ok
### stderr ###
# ...[truncated]
# File "configure.ml", line 121, characters 49-65:
# Warning 3: deprecated: String.uppercase
# Use String.uppercase_ascii instead.
# Looking for ocamlfind package xen-evtchn: ok
# Looking for ocamlfind package xen-gnt.unix: missing
# Error: xenctrl has unsatisfied dependencies but has been requested via the command-line
```

@hannesm suggested fixing it (this worked) by pinning the last working version of `xen-gnt`: `opam pin add xen-gnt 2.2.3`

@yomimono  suggested that it's because someone split `xen-gnt.unix` into a new package, `xen-gnt-unix`, without updating dependencies or testing a mirage build.

**Comment by hannesm** [comment]
my suggestion was a workaround ;)
the actual fix is do adjust some of the dependencies in here...

I wonder whether the jbuilder-front tests mirage unikernels at all (with various backends)... I'm scared to run `opam update` these days since I don't have the time and energy to fix other people's shiny new build systems...  could you please pay some more attention before pushing things into opam-repository (I can also see lots of PRs there which imply that to jbuilder a package, sometimes 3!! releases seem to be necessary to get a package in shape) -- I thought you guys were experts in CI systems and QA!? @avsm @djs55 @samoht (sorry if I missed someone or some memo)

**Comment by djs55** [comment]
Sorry for the temporary glitch -- I added upper bounds on `xen-evtchn` but missed `xen-gnt`: see the linked opam-repository PR.

I think only builds of mirage apps which use `vchan` are affected. `xen-evtchn-unix` and `xen-gnt-unix` contain the Unix userspace C bindings for the `xenctrl` library. This lib isn't used by the Xen backend at all (there's a different implementation in the kernel) and would only be used by the Unix backend by apps which knew they were running on a Xen system such as a user space disk backend. The generic Mirage apps I've been building seem fine.

I'll update the dependencies in this repo shortly.

**Comment by cfcs** [comment]
Shouldn't this be fixed by using the newer interface rather than pinning older versions? This fix seems likely to make it hard to build things in the future.

**Comment by djs55** [comment]
@cfcs the commit that closed this issue does indeed update master to use the new interfaces. Version 2.3.1 of `vchan` has been released with the fix (https://github.com/ocaml/opam-repository/pull/9395) There's also an open PR https://github.com/ocaml/opam-repository/pull/9388 which adds version constraints for the old packages to hopefully avoid trying to install incompatible versions.

Thanks for the bug report!

**Comment by cfcs** [comment]
Ah, cool! I hadn't seen that it was `opam-repository` and assumed it was the `opam` file in this repo. Sorry!
